package org.castor.jaxb.reflection.info;

public interface JaxbFieldNatureProperties {
    String ELEMENTS = "ELEMENTS";
    String ELEMENT_REFS = "ELEMENT_REFS";
    /** ENUM_VALUE. */
    String ENUM_VALUE = "ENUM_VALUE";
    /** ATTRIBUTE_REQUIRED. */
    String ATTRIBUTE_REQUIRED = "ATTRIBUTE_REQUIRED";
    /** ATTRIBUTE_NAMESPACE. */
    String ATTRIBUTE_NAMESPACE = "ATTRIBUTE_NAMESPACE";
    /** ATTRIBUTE_NAME. */
    String ATTRIBUTE_NAME = "ATTRIBUTE_NAME";
    /** ROOT_ELEMENT_NAMESPACE. */
    String ROOT_ELEMENT_NAMESPACE = "ROOT_ELEMENT_NAMESPACE";
    /** ROOT_ELEMENT_NAME. */
    String ROOT_ELEMENT_NAME = "ROOT_ELEMENT_NAME";
    /** ELEMENT_DEFAULT_VALUE. */
    String ELEMENT_DEFAULT_VALUE = "ELEMENT_DEFAULT_VALUE";
    /** ELEMENT_TYPE. */
    String ELEMENT_TYPE = "ELEMENT_TYPE";
    /** ELEMENT_NAMESPACE. */
    String ELEMENT_NAMESPACE = "ELEMENT_NAMESPACE";
    /** ELEMENT_REQUIRED. */
    String ELEMENT_REQUIRED = "ELEMENT_REQUIRED";
    /** ELEMENT_NILLABLE. */
    String ELEMENT_NILLABLE = "ELEMENT_NILLABLE";
    /** ELEMENT_NAME. */
    String ELEMENT_NAME = "ELEMENT_NAME";
    /** HAS_XML_ELEMENT. */
    String HAS_XML_ELEMENT = "HAS_XML_ELEMENT";
    /** HAS_XML_ATTRIBUTE. */
    String HAS_XML_ATTRIBUTE = "HAS_XML_ATTRIBUTE";
    /** HAS_XML_ELEMENTS. */
    String HAS_XML_ELEMENTS = "HAS_XML_ELEMENTS";
    /** HAS_XML_ELEMENT_REF. */
    String HAS_XML_ELEMENT_REF = "HAS_XML_ELEMENT_REF";
    /** HAS_XML_ELEMENT_REFS. */
    String HAS_XML_ELEMENT_REFS = "HAS_XML_ELEMENT_REFS";
    /** HAS_XML_ELEMENT_WRAPPER. */
    String HAS_XML_ELEMENT_WRAPPER = "HAS_XML_ELEMENT_WRAPPER";
    /** HAS_XML_ANY_ELEMENT. */
    String HAS_XML_ANY_ELEMENT = "HAS_XML_ANY_ELEMENT";
    /** HAS_XML_ANY_ATTRIBUTE. */
    String HAS_XML_ANY_ATTRIBUTE = "HAS_XML_ANY_ATTRIBUTE";
    /** HAS_XML_TRANSIENT. */
    String HAS_XML_TRANSIENT = "HAS_XML_TRANSIENT";
    /** HAS_XML_VALUE. */
    String HAS_XML_VALUE = "HAS_XML_VALUE";
    /** HAS_XML_ID. */
    String HAS_XML_ID = "HAS_XML_ID";
    /** HAS_XML_IDREF. */
    String HAS_XML_IDREF = "HAS_XML_IDREF";
    /** HAS_XML_LIST. */
    String HAS_XML_LIST = "HAS_XML_LIST";
    /** HAS_XML_MIXED. */
    String HAS_XML_MIXED = "HAS_XML_MIXED";
    /** HAS_XML_MIME_TYPE. */
    String HAS_XML_MIME_TYPE = "HAS_XML_MIME_TYPE";
    /** HAS_XML_ATTACHMENT_REF. */
    String HAS_XML_ATTACHMENT_REF = "HAS_XML_ATTACHMENT_REF";
    /** HAS_XML_INLINE_BINARY_DATA. */
    String HAS_XML_INLINE_BINARY_DATA = "HAS_XML_INLINE_BINARY_DATA";
    /** HAS_XML_ENUM_VALUE. */
    String HAS_XML_ENUM_VALUE = "HAS_XML_ENUM_VALUE";
    String ELEMENT_REF_NAME = "ELEMENT_REF_NAME";
    String ELEMENT_REF_TYPE = "ELEMENT_REF_TYPE";
    String ELEMENT_REF_NAMESPACE = "ELEMENT_REF_NAMESPACE";
    String ELEMENT_WRAPPER_NAME = "ELEMENT_WRAPPER_NAME";
    String ELEMENT_WRAPPER_NAMESPACE = "ELEMENT_WRAPPER_NAMESPACE";
    String ELEMENT_WRAPPER_NILLABLE = "ELEMENT_WRAPPER_NILLABLE";
    String ELEMENT_WRAPPER_REQUIRED = "ELEMENT_WRAPPER_REQUIRED";
    String ANY_ELEMENT_LAX = "ANY_ELEMENT_LAX";
    String ANY_ELEMENT_DOM_HANDLER = "ANY_ELEMENT_DOM_HANDLER";
    String MIME_TYPE = "MIME_TYPE";
    String XML_JAVA_TYPE_ADAPTER = "XML_JAVA_TYPE_ADAPTER";
}